# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    ubuntu16:
      containerImage: ubuntu:16.04
    ubuntu18:
      containerImage: ubuntu:18.04
    #rhel7:
    #  containerImage: roboxes/rhel7:latest


container: $[ variables['containerImage'] ]

steps:
- script: |
    docker exec -t -u 0 ci-container \
    sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
  displayName: Set up sudo
- script: |
    apt-get install -y curl bzip2
    curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
    bash /tmp/miniconda.sh -bfp /usr/local
    rm -rf /tmp/miniconda.sh
    export PATH="/opt/conda/bin:$PATH"
    conda -V
  displayName: 'Install Miniconda'
