# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

# containers must contain curl & bzip2 in order to install Miniconda.
# Azure has issues with running apt-get inside of contains because of the 
# way it mounts them. Most base images on dockerhub do not contain curl & bzip2
# see https://github.com/Microsoft/azure-pipelines-agent/issues/2043
strategy:
  matrix:
    ubuntu18:
      containerImage: buildpack-deps:18.04-curl
    rhel7:
      containerImage: openshift/base-centos7:latest
    # the condaci container already includes conda
    #condaci:
    #  containerImage: continuumio/miniconda3:latest

container: $[ variables['containerImage'] ]

steps:
- script: |
    curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
    bash /tmp/miniconda.sh -bfp ~/miniconda
    rm -rf /tmp/miniconda.sh
    export PATH="~/miniconda/bin:$PATH"
    conda init bash
    conda create -y -n test python=3 pytest 
    conda -V
  displayName: 'Install miniconda and create a testing env'
- script: |
    export PATH="~/miniconda/bin:$PATH"
    conda init bash
    conda activate test
    pytest --capture=sys -v
  displayName: 'Run Tests'
