trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

# containers must contain curl & bzip2 in order to install Miniconda.
# Azure has issues with running apt-get inside of contains because of the
# way it mounts them. Most base images on dockerhub do not contain curl & bzip2
# see https://github.com/Microsoft/azure-pipelines-agent/issues/2043
strategy:
  matrix:
    ubuntu16:
      containerImage: buildpack-deps:16.04-curl
    ubuntu18:
      containerImage: buildpack-deps:18.04-curl
    rhel7:
      containerImage: openshift/base-centos7:latest
    # the condaci container already includes conda
    #condaci:
    #  containerImage: continuumio/miniconda3:latest

container:
  image: $[ variables['containerImage'] ]
  options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"

steps:
- script: |
    /tmp/docker exec -t -u 0 ci-container \
    sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install bzip2"
  displayName: Set up sudo
- script: |
    curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
    bash /tmp/miniconda.sh -bfp ~/miniconda
    rm -rf /tmp/miniconda.sh
    export PATH="~/miniconda/bin:$PATH"
    eval "$(conda shell.bash hook)"
    conda -V
    conda create -y -n test python=3 pytest
    conda activate test
    pytest --capture=sys -v
  displayName: 'Run Tests'
