# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    ubuntu16:
      containerImage: ubuntu:16.04
    ubuntu18:
      containerImage: ubuntu:18.04
    rhel7:
      containerImage: roboxes/rhel7:latest


container: $[ variables['containerImage'] ]

steps:
- script: |
    curl -sL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh \
      && chmod +x miniconda.sh \
      && ./miniconda.sh -b -p /usr/share/miniconda \
      && rm miniconda.sh

    CONDA=/usr/share/miniconda
    echo "CONDA=$CONDA" | tee -a /etc/environment
    ln -s $CONDA/bin/conda /usr/bin/conda
    conda -V
  displayName: 'Install Miniconda'
- script: |
    conda create -n mirror -c conda-forge conda-mirror
    conda activate mirror
    conda mirror -vv --upstream-channel quansight-small-test --target-directory mirror --platform linux-64
    conda mirror -vv --upstream-channel quansight-small-test --target-directory mirror --platform noarch
    ls -l mirror
  displayName: 'Create Local Mirror'
