# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  containers:
  - container: u16
      image: ubuntu:16.04
      options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
  - container: u18
      image: ubuntu:18.04
      options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
  - container: conda
      image: continuumio/miniconda3:latest


pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    ubuntu16:
      containerResource: u16
    ubuntu18:
      containerResource: u18
    #rhel7:
    #  containerImage: roboxes/rhel7:latest
    #condaci:
    #  containerImage: continuumio/miniconda3:latest

container: $[ variables['containerResource'] ]

steps:
  # using workaround to get sudo - https://github.com/microsoft/azure-pipelines-agent/issues/2043
- script: | 
    /tmp/docker exec -t -u 0 ci-container \
    sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
  displayName: Set up sudo
- script: |
    sudo apt-get install -y curl bzip2
  displayName: Install curl & bzip2
- script: |
    curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
    bash /tmp/miniconda.sh -bfp ~/miniconda
    rm -rf /tmp/miniconda.sh
    export PATH="~/miniconda/bin:$PATH"
    conda -V
  displayName: Install Miniconda
