# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  containers:
  - container: u16
    image: ubuntu:16.04
  - container: u18
    image: ubuntu:18.04

pool:
  vmImage: 'ubuntu-16.04'

#strategy:
#  matrix:
#    ubuntu16:
#      containerResource: buildpack-deps:16.04-scm
#    ubuntu18:
#      containerResource: buildpack-deps:18.04-scm
    #rhel7:
    #  containerImage: roboxes/rhel7:latest
    #condaci:
    #  containerImage: continuumio/miniconda3:latest

container: u16 #$[ variables['containerResource'] ]

steps:
- script: |
    apt-get install curl bzip2
  displayName: Install curl, bzip2
- script: |
    curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
    bash /tmp/miniconda.sh -bfp ~/miniconda
    rm -rf /tmp/miniconda.sh
    export PATH="~/miniconda/bin:$PATH"
    conda -V
  displayName: Install Miniconda
