# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    ubuntu16:
      containerResource: buildpack-deps:16.04-curl
    ubuntu18:
      containerResource: buildpack-deps:18.04-curl
    #rhel7:
    #  containerImage: roboxes/rhel7:latest
    #condaci:
    #  containerImage: continuumio/miniconda3:latest

container: $[ variables['containerResource'] ]

steps:
- script: |
    curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh
    bash /tmp/miniconda.sh -bfp ~/miniconda
    rm -rf /tmp/miniconda.sh
    export PATH="~/miniconda/bin:$PATH"
    conda -V
  displayName: Install Miniconda
